name: beanmind
version: '3.8'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: beanmind
    ports:
      - "3307:3306"
    volumes:
      - beanmind_-ai-coffee-curator_beanmind_mysql_data:/var/lib/mysql

volumes:
  beanmind_-ai-coffee-curator_beanmind_mysql_data:
    external: true
