server:
  port: 3000

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3307}/beanminddev?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: rootpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: wkjeon@gmail.com
    password: misvakcqbfplbdms
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: beanmind_secure_jwt_secret_key_2026_test
  expiration-ms: 86400000

naver:
  client:
    id: ${NAVER_CLIENT_ID:}
    secret: ${NAVER_CLIENT_SECRET:}

gemini:
  api:
    key: ${GEMINI_API_KEY:}
kakao:
  api:
    key: ${KAKAO_REST_API_KEY:}
google:
  places:
    api:
      key: ${GOOGLE_PLACES_API_KEY:}


