/**
 * Global Error Codes for BeanMind Backend
 * These codes are standardized so the Frontend can gracefully handle them using i18n
 */
export const ERROR_CODES = {
    // Auth & Identity
    UNAUTHORIZED: 'ERR_UNAUTHORIZED',
    INVALID_TOKEN: 'ERR_INVALID_TOKEN',
    USER_NOT_FOUND: 'ERR_USER_NOT_FOUND',
    MISSING_AUTH_HEADER: 'ERR_MISSING_AUTH_HEADER',
    PASSWORD_INVALID: 'ERR_PASSWORD_INVALID',
    EMAIL_ALREADY_EXISTS: 'ERR_EMAIL_ALREADY_EXISTS',
    ACCOUNT_LOCKED: 'ERR_ACCOUNT_LOCKED',
    NICKNAME_REQUIRED: 'ERR_NICKNAME_REQUIRED',
    SOCIAL_LOGIN_CANT_CHANGE_PW: 'ERR_SOCIAL_LOGIN_CANT_CHANGE_PW',
    PASSWORD_MISMATCH: 'ERR_PASSWORD_MISMATCH',
    PASSWORD_SAME_AS_OLD: 'ERR_PASSWORD_SAME_AS_OLD',
    INVALID_VERIFICATION_CODE: 'ERR_INVALID_VERIFICATION_CODE',
    LOGIN_FAILED: 'ERR_LOGIN_FAILED',

    // Points & Credits
    INSUFFICIENT_BEANS: 'ERR_INSUFFICIENT_BEANS',
    DAILY_LIMIT_EXCEEDED: 'ERR_DAILY_LIMIT_EXCEEDED',
    INVALID_POINT_AMOUNT: 'ERR_INVALID_POINT_AMOUNT',
    CANNOT_REWARD_YOURSELF: 'ERR_CANNOT_REWARD_YOURSELF',

    // Validation & Params
    MISSING_REQUIRED_FIELDS: 'ERR_MISSING_REQUIRED_FIELDS',
    INVALID_DATA_FORMAT: 'ERR_INVALID_DATA_FORMAT',
    TOO_MANY_REQUESTS: 'ERR_TOO_MANY_REQUESTS',
    ALREADY_IN_COLLECTION: 'ERR_ALREADY_IN_COLLECTION',

    // Resources & AI & Shops
    PRESCRIPTION_NOT_FOUND: 'ERR_PRESCRIPTION_NOT_FOUND',
    STORE_NOT_FOUND: 'ERR_STORE_NOT_FOUND',
    REVIEW_NOT_FOUND: 'ERR_REVIEW_NOT_FOUND',
    POST_NOT_FOUND: 'ERR_POST_NOT_FOUND',
    COMMENT_NOT_FOUND: 'ERR_COMMENT_NOT_FOUND',
    AI_GENERATION_FAILED: 'ERR_AI_GENERATION_FAILED',
    AI_RATE_LIMIT: 'ERR_AI_RATE_LIMIT',
    ROUTING_FAILED: 'ERR_ROUTING_FAILED',
    UNAUTHORIZED_ACTION: 'ERR_UNAUTHORIZED_ACTION',
    STORE_RESUBMIT_NOT_ALLOWED: 'ERR_STORE_RESUBMIT_NOT_ALLOWED',
    MAX_APPROVAL_REQUESTS: 'ERR_MAX_APPROVAL_REQUESTS',

    // Pilgrimage
    STORE_NOT_MAPPED: 'ERR_STORE_NOT_MAPPED',
    GPS_MISSING: 'ERR_GPS_MISSING',
    ALREADY_CHECKED_IN: 'ERR_ALREADY_CHECKED_IN',
    BADGE_NOT_OWNED: 'ERR_BADGE_NOT_OWNED',
    STORE_TOO_FAR: 'ERR_STORE_TOO_FAR',

    // Admin & Sponsorship
    SUPER_ADMIN_REQUIRED: 'ERR_SUPER_ADMIN_REQUIRED',
    AD_NOT_APPROVED: 'ERR_AD_NOT_APPROVED',
    AD_NOT_FOUND: 'ERR_AD_NOT_FOUND',
    ADVERTISER_EXISTS: 'ERR_ADVERTISER_EXISTS',

    // Generic Internal
    INTERNAL_SERVER_ERROR: 'ERR_INTERNAL_SERVER_ERROR',
    DB_CONNECTION_ERROR: 'ERR_DB_CONNECTION_ERROR'
} as const;

export type ErrorCodeType = typeof ERROR_CODES[keyof typeof ERROR_CODES];
